# Generated by Django 3.2.5 on 2021-07-08 11:44

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210708_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.path_and_rename),
        ),
    ]
