# Generated by Django 3.2.5 on 2021-07-09 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_deposithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('deposit_amount', models.FloatField(default=0.0)),
                ('bonus_amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('new_type', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_amount', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Cancel'), (1, 'Acepted')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('payment_id', models.CharField(max_length=250)),
                ('payment_mode', models.CharField(max_length=250)),
                ('payment_source', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(0, 'Not Done'), (1, 'Done')], default=0)),
                ('remarks', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timeperiod', models.TimeField(auto_now_add=True)),
                ('trad_type', models.CharField(max_length=250)),
                ('starting_asset_price', models.FloatField(default=0.0)),
                ('ending_asset_price', models.FloatField(default=0.0)),
                ('trad_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Cancel'), (1, 'Acepted')])),
                ('assert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.assets')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
