# Generated by Django 3.2.5 on 2021-07-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_depositoffers_news_tradhistory_withdrawhistory_withdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')]),
        ),
    ]
