# Generated by Django 3.2.5 on 2021-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoffers',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')]),
        ),
        migrations.AlterField(
            model_name='tradhistory',
            name='trad_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Acepted'), (1, 'Cancel')]),
        ),
        migrations.AlterField(
            model_name='withdrawhistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Decline')], default=0),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Cancel')]),
        ),
    ]
