# Generated by Django 3.2.5 on 2021-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210716_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='status',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='deposithistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')], default=0),
        ),
        migrations.AlterField(
            model_name='tradhistory',
            name='trad_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')]),
        ),
        migrations.AlterField(
            model_name='withdrawhistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')], default=0),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')]),
        ),
    ]
