# Generated by Django 3.2.5 on 2021-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_assets_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')], default=0),
        ),
    ]
