# Generated by Django 3.2.5 on 2021-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_withdrawrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_betting_user',
            field=models.BooleanField(default=False),
        ),
    ]
