# Generated by Django 3.2.5 on 2021-07-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_user_is_betting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
