# Generated by Django 3.2.5 on 2021-07-27 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('market_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')], default=0)),
                ('bet_amount', models.FloatField()),
                ('win_amount', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('market_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')], default=0)),
                ('digit', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('game_type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('open_single_result', models.CharField(max_length=250)),
                ('open_triple_result', models.CharField(max_length=250)),
                ('close_single_result', models.CharField(max_length=250)),
                ('close_triple_result', models.CharField(max_length=250)),
                ('close_jodi_result', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('market_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')], default=0)),
                ('digit', models.FloatField()),
                ('win_amount', models.FloatField()),
                ('game_name', models.CharField(max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_amount', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')], default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_request_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('payment_id', models.CharField(max_length=250)),
                ('payment_mode', models.CharField(max_length=250)),
                ('payment_source', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')], default=0)),
                ('remarks', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriplePattiBetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martet_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')])),
                ('market_game_type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')])),
                ('points', models.CharField(max_length=250)),
                ('digit', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')])),
                ('game_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.gameprice')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.marketgame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePattiBetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martet_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')])),
                ('market_game_type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')])),
                ('points', models.CharField(max_length=250)),
                ('digit', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')])),
                ('game_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.gameprice')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.marketgame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleDigitBetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martet_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')])),
                ('market_game_type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')])),
                ('points', models.CharField(max_length=250)),
                ('digit', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')])),
                ('game_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.gameprice')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.marketgame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JodiBetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martet_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')])),
                ('market_game_type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')])),
                ('points', models.CharField(max_length=250)),
                ('digit', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')])),
                ('game_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.gameprice')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.marketgame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoublePattiBetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martet_category', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')])),
                ('market_game_type', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')])),
                ('points', models.CharField(max_length=250)),
                ('digit', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')])),
                ('game_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.gameprice')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.marketgame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('bonus_amount', models.FloatField()),
                ('payment_id', models.CharField(max_length=250)),
                ('payment_mode', models.CharField(max_length=250)),
                ('payment_source', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Decline')], default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
