# Generated by Django 3.2.5 on 2021-07-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketgame',
            name='close_result_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketgame',
            name='open_result_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
