# Generated by Django 3.2.5 on 2021-07-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0002_auto_20210727_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='close_jodi_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='close_single_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='close_triple_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='digit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='open_single_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='open_triple_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
