# Generated by Django 3.2.5 on 2021-07-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0003_auto_20210727_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketgame',
            name='game_type',
        ),
        migrations.AddField(
            model_name='marketgame',
            name='game_type_close',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketgame',
            name='game_type_open',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
