# Generated by Django 3.2.5 on 2021-07-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0004_auto_20210727_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketgame',
            name='game_type',
            field=models.IntegerField(blank=True, choices=[(0, 'OPEN'), (1, 'CLOSE')], null=True),
        ),
    ]
