# Generated by Django 3.2.5 on 2021-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0006_auto_20210727_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='status',
            field=models.IntegerField(blank=True, default=[(0, 'Betting is Closed For Today'), (1, 'Batting is Running Now')], null=True),
        ),
        migrations.AlterField(
            model_name='starlinegame',
            name='status',
            field=models.IntegerField(blank=True, default=[(0, 'Betting is Closed For Today'), (1, 'Batting is Running Now')], null=True),
        ),
    ]
