# Generated by Django 3.2.5 on 2021-07-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0007_auto_20210727_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Betting is Closed For Today'), (1, 'Batting is Running Now')], null=True),
        ),
    ]
