# Generated by Django 3.2.5 on 2021-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0008_alter_marketgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='status',
            field=models.IntegerField(choices=[(0, 'Betting is Closed For Today'), (1, 'Batting is Running Now')]),
        ),
    ]
