# Generated by Django 3.2.5 on 2021-08-02 06:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bettingapp', '0009_alter_marketgame_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitNumberHistroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(max_length=250)),
                ('open_single_result', models.CharField(blank=True, max_length=250, null=True)),
                ('open_triple_result', models.CharField(blank=True, max_length=250, null=True)),
                ('close_single_result', models.CharField(blank=True, max_length=250, null=True)),
                ('close_triple_result', models.CharField(blank=True, max_length=250, null=True)),
                ('close_jodi_result', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketGameBiddingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('market_type', models.IntegerField(choices=[(0, 'Main'), (1, 'Star Line')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(max_length=250)),
                ('game_category', models.CharField(max_length=250)),
                ('bidding_digit', models.CharField(max_length=250)),
                ('bidding_points', models.FloatField(default=0.0)),
                ('bidding_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bidding_time', models.TimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('market_game_bidding_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_game_bid_type', to='bettingapp.marketgamebiddingtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(max_length=250)),
                ('game_category', models.CharField(max_length=250)),
                ('bidding_digit', models.CharField(max_length=250)),
                ('win_bidding_digit', models.IntegerField(default=0)),
                ('bidding_points', models.FloatField(default=0.0)),
                ('bidding_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bidding_time', models.TimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('market_game_bidding_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_game_bid_type', to='bettingapp.marketgamebiddingtype')),
            ],
        ),
        migrations.RemoveField(
            model_name='doublepattibetting',
            name='game_price_id',
        ),
        migrations.RemoveField(
            model_name='doublepattibetting',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='doublepattibetting',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='jodibetting',
            name='game_price_id',
        ),
        migrations.RemoveField(
            model_name='jodibetting',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='jodibetting',
            name='star_line_id',
        ),
        migrations.RemoveField(
            model_name='jodibetting',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='singledigitbetting',
            name='game_price_id',
        ),
        migrations.RemoveField(
            model_name='singledigitbetting',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='singledigitbetting',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='singlepattibetting',
            name='game_price_id',
        ),
        migrations.RemoveField(
            model_name='singlepattibetting',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='singlepattibetting',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='TopWinner',
        ),
        migrations.RemoveField(
            model_name='triplepattibetting',
            name='game_price_id',
        ),
        migrations.RemoveField(
            model_name='triplepattibetting',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='triplepattibetting',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='gameprice',
            old_name='market_category',
            new_name='market_type',
        ),
        migrations.RenameField(
            model_name='marketgame',
            old_name='market_category',
            new_name='market_type',
        ),
        migrations.RemoveField(
            model_name='marketgame',
            name='digit',
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='game_type',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='DoublePattiBetting',
        ),
        migrations.DeleteModel(
            name='JodiBetting',
        ),
        migrations.DeleteModel(
            name='SingleDigitBetting',
        ),
        migrations.DeleteModel(
            name='SinglePattiBetting',
        ),
        migrations.DeleteModel(
            name='StarLineGame',
        ),
        migrations.DeleteModel(
            name='TriplePattiBetting',
        ),
        migrations.AddField(
            model_name='userwinner',
            name='market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_market_game', to='bettingapp.marketgame'),
        ),
        migrations.AddField(
            model_name='userwinner',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbetting',
            name='market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_on_market_game', to='bettingapp.marketgame'),
        ),
        migrations.AddField(
            model_name='userbetting',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitnumberhistroy',
            name='market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_market_game', to='bettingapp.marketgame'),
        ),
    ]
