# Generated by Django 3.2.5 on 2021-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0010_auto_20210802_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketgame',
            name='date',
        ),
        migrations.AddField(
            model_name='marketgame',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marketgame',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
