# Generated by Django 3.2.5 on 2021-08-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0011_auto_20210802_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='game_type_close',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='game_type_open',
            field=models.CharField(max_length=250),
        ),
    ]
