# Generated by Django 3.2.5 on 2021-08-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0013_alter_marketgame_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='game_type_close',
            field=models.CharField(default='close', max_length=250),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='game_type_open',
            field=models.CharField(default='open', max_length=250),
        ),
    ]
