# Generated by Django 3.2.5 on 2021-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0014_auto_20210803_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
