# Generated by Django 3.2.5 on 2021-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0015_auto_20210803_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgame',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketgame',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
