# Generated by Django 3.2.5 on 2021-08-04 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bettingapp', '0016_auto_20210803_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbetting',
            name='market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_on_market_game_id', to='bettingapp.marketgame'),
        ),
        migrations.AlterField(
            model_name='userbetting',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_by_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
