# Generated by Django 3.2.5 on 2021-08-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0019_auto_20210804_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbetting',
            old_name='user_id',
            new_name='user_id_id',
        ),
    ]
