# Generated by Django 3.2.5 on 2021-08-04 09:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bettingapp', '0020_rename_user_id_userbetting_user_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbetting',
            old_name='user_id_id',
            new_name='user_id',
        ),
        migrations.CreateModel(
            name='UsersBettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(max_length=250)),
                ('game_category', models.CharField(max_length=250)),
                ('bidding_digit', models.CharField(max_length=250)),
                ('bidding_points', models.FloatField(default=0.0)),
                ('bidding_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bidding_time', models.TimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('market_game_bidding_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.marketgamebiddingtype')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettingapp.marketgame')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
