# Generated by Django 3.2.5 on 2021-08-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0021_auto_20210804_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersBettings',
        ),
    ]
